server.address=0.0.0.0
server.port=8443

server.ssl.enabled=true
server.ssl.key-store=classpath:certs/terminal-nav.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=changeit
server.ssl.key-password=changeit
server.ssl.key-alias=terminal-nav
